LOAD 'age';
SET search_path = ag_catalog, "$user", public;

SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_01', name: 'Aguacatillo', fee: 30.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_02', name: 'Penal', fee: 30.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_03', name: 'Caseta', fee: 50.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_04', name: 'Fundición', fee: 50.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_05', name: 'Toma', fee: 80.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_06', name: 'Mirador', fee: 80.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_07', name: 'Parador Turístico', fee: 80.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_08', name: 'Tierra de Agave', fee: 80.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_09', name: 'San Pedro', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_10', name: 'Santa Ana', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_11', name: 'Medineño', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_12', name: 'Cantaritos El Güero', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_13', name: 'Amatitán', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_14', name: 'Puerta de En Medio', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_15', name: 'San Martín', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_16', name: 'Magdalena', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (z:Zone {id: 'zon_17', name: 'Santa Teresa', fee: 100.0, is_rural: true}) RETURN z $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'ENTREMESES', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ent_01', name: 'Tataki (Ceviche)', price: 160.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ent_02', name: 'Aguachile', price: 170.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ent_03', name: 'Rollo Primavera', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ent_04', name: 'Gyosas', price: 110.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'KUSHIAGE_BROCHETAS', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_kush_01', name: 'Kushiage de Res', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_kush_02', name: 'Kushiage de Camarón', price: 110.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_kush_03', name: 'Kushiage de Pollo', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'ENSALADAS', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ens_01', name: 'Ensalada de Pollo', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ens_02', name: 'Ensalada de Res', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ens_03', name: 'Ensalada de Mariscos', price: 160.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_ens_04', name: 'Ensalada Verde', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'SASHIMI', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sash_01', name: 'Sashimi de Salmón', price: 170.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sash_02', name: 'Sashimi de Res', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sash_03', name: 'Sashimi de Pescado', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sash_04', name: 'Sashimi de Pulpo', price: 200.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'NIGIRIS', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_nig_01', name: 'Nigiri Ebi (Camarón)', price: 20.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_nig_02', name: 'Nigiri Tako (Pulpo)', price: 20.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_nig_03', name: 'Nigiri Kanikama (Cangrejo)', price: 15.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_nig_04', name: 'Nigiri Syake (Salmón)', price: 20.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_nig_05', name: 'Nigiri Banana (Plátano)', price: 15.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'SOPAS', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sop_01', name: 'Udon', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sop_02', name: 'Sopa Especial', price: 160.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sop_03', name: 'Ramen', price: 190.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'YAKIMESHI', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_yaki_01', name: 'Yakimeshi de Verduras', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_yaki_02', name: 'Yakimeshi de Carne (Res)', price: 75.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_yaki_03', name: 'Yakimeshi de Pollo', price: 80.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_yaki_04', name: 'Yakimeshi de Camarón', price: 80.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_yaki_05', name: 'Yakimeshi Mixto', price: 85.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_yaki_06', name: 'Yakimeshi Tonkotsu', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'TEPPANYAKI_TERIYAKI', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_tepp_01', name: 'Teppanyaki / Teriyaki de Filete (Pescado)', price: 130.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_tepp_02', name: 'Teppanyaki / Teriyaki de Res', price: 135.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_tepp_03', name: 'Teppanyaki / Teriyaki de Pollo', price: 140.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_tepp_04', name: 'Teppanyaki / Teriyaki de Camarón', price: 145.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_tepp_05', name: 'Teppanyaki / Teriyaki Mixto', price: 155.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_tepp_06', name: 'Teppanyaki / Teriyaki de Salmón', price: 200.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'PLATILLOS_FUERTES', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_01', name: 'Verduras Salteadas', price: 80.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_02', name: 'Sakana Furai', price: 135.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_03', name: 'Ebi Furai', price: 135.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_04', name: 'Tori Karaage', price: 140.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_05', name: 'Milanesa de Pollo o Res', price: 140.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_06', name: 'Udon Plancha', price: 140.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_07', name: 'Chow Mein', price: 140.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_08', name: 'Brochetas Yakitori', price: 145.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_09', name: 'Camarones Kimono', price: 145.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_10', name: 'Camarones Philadelphia', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_11', name: 'Tempura Ebi', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_12', name: 'Spaguetti de Mariscos', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_13', name: 'Ebydon', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_14', name: 'Fire Mixto', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_15', name: 'Filete de Pescado Especial', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_16', name: 'Filete de Pollo Especial', price: 165.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pf_17', name: 'Puerquitos Locos', price: 170.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'SUSHI_ROLLOS', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_01', name: 'Sushi Empanizado', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_02', name: 'Sushi Philadelphia', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_03', name: 'Sushi California', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_04', name: 'Kani Roll', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_05', name: 'Esfera Dragón Ball', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_06', name: 'Chipotle Roll', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_07', name: 'Avocado Roll', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_08', name: 'Arcoiris Roll Especial', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_09', name: 'Hulk', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_10', name: 'Eby Roll', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_11', name: 'Plátano Roll', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_12', name: 'Salmón Roll', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_13', name: 'México Roll', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_14', name: 'Philadelphia Empanizado', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_15', name: 'Furia Roll', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_16', name: 'Pink Salmón', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_17', name: 'Oishi Roll Especial', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_18', name: 'Flamin Hot', price: 105.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_19', name: 'Sushi Masago', price: 110.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_20', name: 'Empanizado Especial', price: 115.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_21', name: 'Tocayo Roll', price: 115.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_22', name: 'Mar y Tierra', price: 115.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_23', name: 'Mechudo', price: 120.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_24', name: 'Eby Roll Especial', price: 120.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_25', name: 'Especial Ryü', price: 120.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_26', name: 'Especial No. 1', price: 120.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_27', name: 'Zizi Roll Especial', price: 130.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_28', name: 'Hulk Especial', price: 130.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_29', name: 'Tuna Roll', price: 130.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_30', name: 'Cheese Explosion', price: 135.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_31', name: 'Panchito', price: 140.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_32', name: 'Tocino Roll', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_sush_33', name: 'Tabla de Sushi Mixta', price: 300.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'BEBIDAS', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_01', name: 'Refresco (500ml)', price: 35.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_02', name: 'Té Jazmín Frío (Vaso Individual)', price: 35.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_03', name: 'Té Jazmín Frío (Jarra 3.5 Litros)', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_04', name: 'Limonada / Naranjada', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_05', name: 'Calpico 1/2 Litro', price: 30.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_06', name: 'Calpico 1 Litro', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_07', name: 'Calpico (Jarra 3.5 Litros)', price: 110.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_08', name: 'Calpico Mineral 1/2 Litro', price: 35.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_09', name: 'Calpico Mineral 1 Litro', price: 45.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_10', name: 'Calpico Mineral (Jarra 3.5 Litros)', price: 120.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_11', name: 'Calpico Frutos Rojos (1/2 Litro)', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_12', name: 'Michelada', price: 90.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_beb_13', name: 'Cerveza Corona (330ml)', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'POSTRES', menu: 'JAPANESE'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pos_01', name: 'Brochetas Dulces de Plátano', price: 60.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'jp_pos_02', name: 'Helado Frito', price: 75.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'PLATILLOS', menu: 'ITALIAN'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'it_pla_01', name: 'Lasagna Tradicional', price: 150.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'it_pla_02', name: 'Boloñesa', price: 120.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'it_pla_03', name: 'Fettuccine Alfredo', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'SODAS_ITALIANAS', menu: 'ITALIAN'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'it_sod_01', name: 'Soda Italiana Fresa-Boba', price: 45.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'it_sod_02', name: 'Soda Italiana Piña-Boba', price: 45.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'it_sod_03', name: 'Soda Italiana Mora Azul-Boba', price: 45.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'PAQUETES_Y_PROMOS', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_paq_04', name: 'Promo Hot Dog (3 piezas)', price: 70.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_com_04', name: 'Combo Nuggets', price: 110.0, is_combo: true}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_com_03', name: 'Combo Individual 2', price: 140.0, is_combo: true}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_com_02', name: 'Combo Individual 1', price: 145.0, is_combo: true}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_paq_03', name: 'Paquete 3', price: 150.0, is_combo: true}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_com_01', name: 'Combo Ryu Especial', price: 150.0, is_combo: true}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_paq_01', name: 'Paquete Mix', price: 200.0, is_combo: true}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_paq_05', name: 'Promo Tortas (3 Tortas Teleras)', price: 200.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_paq_02', name: 'Pa Que Compartas', price: 210.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_paq_06', name: 'Caja Ryu Mix', price: 420.0, is_combo: true}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'HAMBURGUESAS', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_01', name: 'Hamburguesa de Res', price: 55.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_02', name: 'Hamburguesa de Pollo a la Plancha', price: 55.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_03', name: 'Hamburguesa de Pollo Empanizado', price: 65.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_04', name: 'Hamburguesa de Camarón', price: 70.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_08', name: 'Hamburguesa Hawaiana', price: 80.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_10', name: 'Hamburguesa Big Ryu', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_07', name: 'Hamburguesa Especial', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_09', name: 'Hamburguesa Cielo Mar y Tierra', price: 120.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_05', name: 'Hamburguesa Ranchera Especial', price: 125.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_ham_06', name: 'Hamburguesa Carolina Especial', price: 125.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'HOT_DOGS', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_hd_01', name: 'Hot Dog Sencillo', price: 25.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_hd_02', name: 'Hot Dog Supremo', price: 90.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_hd_03', name: 'Hot Dog Godzilla', price: 135.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'TORTAS', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_tor_01', name: 'Torta de Telera', price: 90.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_tor_02', name: 'Torta Ranchera Especial', price: 125.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_tor_03', name: 'Torta Carolina Especial', price: 125.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'SNACKS_FRITOS_Y_PAPAS', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_snk_01', name: 'Dedos de Queso', price: 95.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_snk_04', name: 'Aros de Cebolla', price: 90.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pap_02', name: 'Papas a la Francesa', price: 65.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pap_01', name: 'Papas Gajo', price: 80.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_snk_02', name: 'Alitas (Orden individual 10 piezas)', price: 100.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_snk_03', name: 'Boneless (Orden individual 10 piezas)', price: 110.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pak_ali_10', name: 'Pack 10 Alitas', price: 130.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pak_ali_15', name: 'Pack 15 Alitas', price: 170.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pak_ali_20', name: 'Pack 20 Alitas', price: 260.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pak_ali_30', name: 'Pack 30 Alitas', price: 390.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'TOPPINGS_EXTRAS', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_02', name: 'Queso Amarillo', price: 5.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_04', name: 'Cebolla Asada', price: 10.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_06', name: 'Jamón', price: 10.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_01', name: 'Tocino', price: 15.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_03', name: 'Queso Oaxaca', price: 15.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_05', name: 'Piña', price: 20.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_07', name: 'Salsa Ranch', price: 20.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_top_08', name: 'Aderezo Extra', price: 20.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'BEBIDAS', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_10', name: 'Botella de Agua 500ml', price: 12.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_11', name: 'Botella de Agua 1 Litro', price: 15.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_01', name: 'Refresco (500ml)', price: 35.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_02', name: 'Té Jazmín Frío', price: 35.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_03', name: 'Limonada / Naranjada', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_04', name: 'Calpico 1/2 Litro', price: 30.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_05', name: 'Calpico 1 Litro', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_06', name: 'Calpico Mineral 1/2 Litro', price: 35.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_07', name: 'Calpico Mineral 1 Litro', price: 45.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_08', name: 'Calpico Frutos Rojos (1/2 Litro)', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_09', name: 'Michelada', price: 90.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_beb_12', name: 'Cerveza Corona (330ml)', price: 40.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (c:Category {name: 'POSTRES', menu: 'SNACKS'}) RETURN c $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pos_01', name: 'Helado Frito', price: 60.0, is_combo: false}) RETURN d $$) as (v agtype);
SELECT * FROM cypher('ryu_knowledge_graph', $$ MERGE (d:Dish {id: 'sn_pos_02', name: 'Brochetas de Plátano Frito', price: 55.0, is_combo: false}) RETURN d $$) as (v agtype);