# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ryu_telephony.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ryu_telephony.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ryu_telephony.proto\x12\x15ryu.telephony.session\"\x94\x01\n\x0eLatencyMetrics\x12\x17\n\x0fstt_latency_sec\x18\x01 \x01(\x01\x12\x17\n\x0fllm_latency_sec\x18\x02 \x01(\x01\x12\x17\n\x0fkag_latency_sec\x18\x03 \x01(\x01\x12\x17\n\x0ftts_latency_sec\x18\x04 \x01(\x01\x12\x1e\n\x16total_turn_latency_sec\x18\x05 \x01(\x01\"\xbc\x02\n\nSpeechTurn\x12\x12\n\nturn_index\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x33\n\x07speaker\x18\x03 \x01(\x0e\x32\".ryu.telephony.session.SpeakerRole\x12\x16\n\x0eraw_transcript\x18\x04 \x01(\t\x12\x14\n\x0c\x63leaned_text\x18\x05 \x01(\t\x12\x1b\n\x13recognized_entities\x18\x06 \x03(\t\x12\x1a\n\x12\x61ssistant_response\x18\x07 \x01(\t\x12\x36\n\x07metrics\x18\x08 \x01(\x0b\x32%.ryu.telephony.session.LatencyMetrics\x12\x1a\n\x12was_fact_corrected\x18\t \x01(\x08\x12\x17\n\x0f\x63orrection_note\x18\n \x01(\t\"\x92\x02\n\x0b\x43\x61llSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61ller_phone\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61ller_name\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x1a\n\x12total_duration_sec\x18\x06 \x01(\x01\x12\x17\n\x0forder_completed\x18\x07 \x01(\x08\x12\x1b\n\x13\x61ssociated_order_id\x18\x08 \x01(\t\x12\x30\n\x05turns\x18\t \x03(\x0b\x32!.ryu.telephony.session.SpeechTurn\x12\x1a\n\x12termination_reason\x18\n \x01(\t*K\n\x0bSpeakerRole\x12\x17\n\x13SPEAKER_UNSPECIFIED\x10\x00\x12\x08\n\x04USER\x10\x01\x12\r\n\tASSISTANT\x10\x02\x12\n\n\x06SYSTEM\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ryu_telephony_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEAKERROLE']._serialized_start=793
  _globals['_SPEAKERROLE']._serialized_end=868
  _globals['_LATENCYMETRICS']._serialized_start=47
  _globals['_LATENCYMETRICS']._serialized_end=195
  _globals['_SPEECHTURN']._serialized_start=198
  _globals['_SPEECHTURN']._serialized_end=514
  _globals['_CALLSESSION']._serialized_start=517
  _globals['_CALLSESSION']._serialized_end=791
# @@protoc_insertion_point(module_scope)
